all:
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3.11
    archive_destination_path: /opt/confluent
    confluent_cli_archive_destination_path: /opt/confluent-cli
    kraft_enabled: true
    default_internal_replication_factor: 2
    kafka_broker_default_replication_factor: 2
    kafka_broker_min_insync_replicas: 2
    kafka_broker_offsets_topic_replication_factor: 2
    kafka_broker_transaction_state_log_replication_factor: 2
    kafka_broker_transaction_state_log_min_isr: 2

    schema_registry_custom_properties:
      kafkastore.replication.factor: 2

    kafka_connect_custom_properties:
      config.storage.replication.factor: 2
      offset.storage.replication.factor: 2
      status.storage.replication.factor: 2
      group.id: connect-cluster
      config.storage.topic: connect-cluster-configs
      offset.storage.topic: connect-cluster-offsets
      status.storage.topic: connect-cluster-status
      listeners: https://0.0.0.0:8083
      rest.advertised.listener: https
      rest.advertised.host.name: Ginidspwork01.giniminds.local
      rest.advertised.port: "8083"
      confluent.connect.cluster.id: connect-cluster
      confluent.metadata.server.urls: https://Ginidspwork01.giniminds.local:8090,https://Ginidspmast01.giniminds.local:8090
      #confluent.metadata.ssl.endpoint.identification.algorithm: ""

    installation_method: archive
    confluent_archive_file_source: /opt/cp-ansible/confluent-8.1.1.tar.gz
    confluent_archive_file_remote: false
#    kafka_controller_health_checks_enabled: false
#    kafka_broker_health_checks_enabled: false
#    kafka_connect_health_checks_enabled: false
#    schema_registry_health_checks_enabled: false
#    control_center_next_gen_health_checks_enabled: false
#    control_center_next_gen_dependency_health_checks_enabled: false

    ssl_enabled: true
    ssl_mutual_auth_enabled: true
    self_signed: true
    #ssl_custom_certs: true
    regenerate_ca: false
    regenerate_keystore_and_truststore: true
    ssl_self_signed_ca_cert_filepath: /opt/cp-ansible/certs/ca-cert
    ssl_self_signed_ca_key_filepath: /opt/cp-ansible/certs/ca-key
    ssl_self_signed_ca_password: "gini@321"
    ssl_san_extension: true

    ssl_self_signed_organization: GINIMINDS
    ssl_self_signed_organizational_unit: DSP
    ssl_self_signed_location: BANGALORE
    ssl_self_signed_state: KARNATAKA
    ssl_self_signed_country: IN

    rbac_enabled: true
#    auth_mode: mtls

    ## Principal mapping — correct variable name
    principal_mapping_rules:
      - "RULE:.*CN=([a-zA-Z0-9._@-]*).*$/$1/"
      - "DEFAULT"

    ## Impersonation — needed for CC, SR, Connect to work
    impersonation_super_users:
      - 'control_center'
#      - 'kafka_controller'
#      - 'schema_registry'
#      - 'kafka_connect'
#      - 'kafka_broker'

    rbac_component_additional_system_admins:
      - User:admin
#      - User:control_center


    ## MDS super user — matches LDAP cn=admin
    mds_super_user: admin
    mds_super_user_password: Admin123

    ## Service account credentials — match LDAP cn
    kafka_broker_ldap_user: kafka_broker
    kafka_broker_ldap_password: Broker123

    schema_registry_ldap_user: schema_registry
    schema_registry_ldap_password: SR123

    kafka_connect_ldap_user: kafka_connect
    kafka_connect_ldap_password: Connect123

    control_center_next_gen_ldap_user: control_center
    control_center_next_gen_ldap_password: C3123

    create_mds_certs: true

    ## ----------------------------------------
    ## LDAP
    ## ----------------------------------------
    kafka_broker_custom_properties:
      ldap.java.naming.factory.initial: com.sun.jndi.ldap.LdapCtxFactory
      ldap.java.naming.provider.url: ldap://Ginidspmast01.giniminds.local:389
      ldap.java.naming.security.principal: cn=admin,dc=giniminds,dc=local
      ldap.java.naming.security.credentials: Admin123
      ldap.java.naming.security.authentication: simple
      ldap.search.mode: GROUPS
      ldap.user.search.base: ou=users,dc=giniminds,dc=local
      ldap.group.search.base: ou=groups,dc=giniminds,dc=local
      ldap.user.name.attribute: cn
      ldap.user.memberof.attribute: memberOf
      ldap.group.name.attribute: cn
      ldap.group.member.attribute: member
      ldap.user.object.class: inetOrgPerson
      ldap.group.object.class: groupOfNames

      #ssl.principal.mapping.rules: "RULE:.*CN=([a-zA-Z0-9._@-]*),.*$/$1/L,DEFAULT"
      ## Per listener rules — must override DEFAULT
      #listener.name.broker.ssl.principal.mapping.rules: "RULE:.*CN=([a-zA-Z0-9._@-]*),.*$/$1/L,DEFAULT"
      #listener.name.client.ssl.principal.mapping.rules: "RULE:.*CN=([a-zA-Z0-9._@-]*),.*$/$1/L,DEFAULT"
      #listener.name.controller.ssl.principal.mapping.rules: "RULE:.*CN=([a-zA-Z0-9._@-]*),.*$/$1/L,DEFAULT"
      #listener.name.internal.ssl.principal.mapping.rules: "RULE:.*CN=([a-zA-Z0-9._@-]*),.*$/$1/L,DEFAULT"
      #confluent.metadata.server.auth.ssl.principal.mapping.rules: "RULE:.*CN=([a-zA-Z0-9._@-]*),.*$/$1/L,DEFAULT"
      #kafka.rest.auth.ssl.principal.mapping.rules: "RULE:.*CN=([a-zA-Z0-9._@-]*),.*$/$1/L,DEFAULT"

    kafka_broker_custom_listeners:
      internal:
        name: INTERNAL
        port: 9092
        ssl_enabled: true
        ssl_client_authentication: required
        sasl_protocol: none
      broker:
        name: BROKER
        port: 9091
        ssl_enabled: true
        ssl_client_authentication: required
        sasl_protocol: none
      client_listener:
        name: CLIENT
        port: 9097
        ssl_enabled: true
        ssl_client_authentication: required
        sasl_protocol: none

#    jolokia_enabled: true
#    jolokia_url_remote: false
#    jolokia_jar_url: /opt/cp-ansible/jolokia.jar

    jmxexporter_enabled: true
    jmxexporter_url_remote: false
    jmxexporter_jar_url: /opt/cp-ansible/jmx_prometheus_javaagent-0.12.0.jar

  children:
    kafka_controller:
      hosts:
        Ginidspwork01.giniminds.local:
          ssl_keystore_subject_cn: kafka_controller
        Ginidspmast01.giniminds.local:
          ssl_keystore_subject_cn: kafka_controller

    kafka_broker:
      hosts:
        Ginidspwork01.giniminds.local:
          ssl_keystore_subject_cn: kafka_broker
        Ginidspmast01.giniminds.local:
          ssl_keystore_subject_cn: kafka_broker

    schema_registry:
      hosts:
        Ginidspwork01.giniminds.local:
          ssl_keystore_subject_cn: schema_registry

    kafka_connect:
      hosts:
        Ginidspwork01.giniminds.local:
          ssl_keystore_subject_cn: kafka_connect

    control_center_next_gen:
      hosts:
        Ginidspwork01.giniminds.local:
          ssl_keystore_subject_cn: control_center

      vars:
        control_center_next_gen_dependency_alertmanager_port: 9098
        control_center_next_gen_dependency_alertmanager_service_environment_overrides:
          ALERTMANAGER_PORT: "9098"
          ALERTMANAGER_HOST: "10.10.20.41"
#          WEBLISTENADDRESS: "Ginidspwork01.giniminds.local:9098"

        control_center_next_gen_custom_properties:
          confluent.controlcenter.internal.topics.replication: 2
          confluent.controlcenter.command.topic.replication: 2
          confluent.monitoring.interceptor.topic.replication: 2
          confluent.metrics.topic.replication: 2
          confluent.controlcenter.internal.topics.partitions: 2
          confluent.controlcenter.connect.connect-cluster.cluster: https://Ginidspwork01.giniminds.local:8083
